### ISSUE TITLE
mvn install error

### ISSUE THREAD

**Issue by borgymanotoy** [NetoDevel/cli-spring-boot-scaffold#30]
spring-1.5.4.RELEASE

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: C:\maven\bin\..
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: C:\jdk1.8.0_121\jre
Default locale: en_PH, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**ERROR (Maven Install)**
C:\projects\cli-spring-boot-scaffold>mvn install
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for br.com.netodevel:spring-scaffold-cli:jar:0.0.1-SNAPSHOT
[WARNING] 'parent.relativePath' of POM br.com.netodevel:spring-scaffold-cli:0.0.1-SNAPSHOT (C:\projects\cli-spring-boot-scaffold\spring-scaffold-cli\pom.xml) points at br.com.netodevel:spring-boot-cli instead of org.springframework.boot:spring-boot-starter-parent, please verify your project structure @ line 8, column 10
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] spring-boot-generate
[INFO] spring-scaffold-cli
[INFO] Spring generate api scaffold kotlin
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building spring-boot-generate 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The artifact org.apache.commons:commons-io:jar:1.3.2 has been relocated to commons-io:commons-io:jar:1.3.2
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ spring-boot-generate ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] Copying 13 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ spring-boot-generate ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 25 source files to C:\projects\cli-spring-boot-scaffold\spring-boot-generate\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/repository/UserRepository.java:[3,47] package org.springframework.data.jpa.repository does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[5,24] package javax.validation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[7,33] package org.hibernate.service.spi does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[12,47] package org.springframework.web.bind.annotation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[13,47] package org.springframework.web.bind.annotation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[14,47] package org.springframework.web.bind.annotation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[15,47] package org.springframework.web.bind.annotation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[16,47] package org.springframework.web.bind.annotation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[17,47] package org.springframework.web.bind.annotation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[18,47] package org.springframework.web.bind.annotation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[19,51] package org.springframework.web.servlet.mvc.support does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[20,28] package br.com.example.model does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[24,2] cannot find symbol
  symbol: class RequestMapping
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[4,47] package org.springframework.data.jpa.repository does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[6,28] package br.com.example.model does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[8,50] package org.springframework.transaction.annotation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[12,2] cannot find symbol
  symbol: class Transactional
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[52,59] cannot find symbol
  symbol:   class User
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[58,53] cannot find symbol
  symbol:   class User
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[58,88] cannot find symbol
  symbol:   class RedirectAttributes
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[84,53] cannot find symbol
  symbol:   class User
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[84,88] cannot find symbol
  symbol:   class RedirectAttributes
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[97,62] cannot find symbol
  symbol:   class RedirectAttributes
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[18,21] cannot find symbol
  symbol:   class User
  location: class br.com.example.service.UserService
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[22,16] cannot find symbol
  symbol:   class User
  location: class br.com.example.service.UserService
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[27,26] cannot find symbol
  symbol:   class User
  location: class br.com.example.service.UserService
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[27,16] cannot find symbol
  symbol:   class User
  location: class br.com.example.service.UserService
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[32,28] cannot find symbol
  symbol:   class User
  location: class br.com.example.service.UserService
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[35,10] cannot find symbol
  symbol:   class GetMapping
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[43,42] cannot find symbol
  symbol:   class PathVariable
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[42,10] cannot find symbol
  symbol:   class GetMapping
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[52,44] cannot find symbol
  symbol:   class ModelAttribute
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[51,10] cannot find symbol
  symbol:   class GetMapping
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[58,31] cannot find symbol
  symbol:   class Valid
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[58,38] cannot find symbol
  symbol:   class ModelAttribute
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[57,10] cannot find symbol
  symbol:   class PostMapping
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[71,44] cannot find symbol
  symbol:   class PathVariable
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[70,10] cannot find symbol
  symbol:   class GetMapping
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[84,31] cannot find symbol
  symbol:   class Valid
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[84,38] cannot find symbol
  symbol:   class ModelAttribute
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[83,10] cannot find symbol
  symbol:   class PutMapping
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[97,31] cannot find symbol
  symbol:   class PathVariable
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[96,10] cannot find symbol
  symbol:   class DeleteMapping
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[26,10] cannot find symbol
  symbol:   class Transactional
  location: class br.com.example.service.UserService
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[31,10] cannot find symbol
  symbol:   class Transactional
  location: class br.com.example.service.UserService
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[37,22] cannot find symbol
  symbol:   class User
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[45,25] cannot find symbol
  symbol:   class User
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[59,17] cannot find symbol
  symbol:   class User
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[74,33] cannot find symbol
  symbol:   class User
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[78,35] cannot find symbol
  symbol:   class ServiceException
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[85,17] cannot find symbol
  symbol:   class User
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[100,33] cannot find symbol
  symbol:   class User
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[106,35] cannot find symbol
  symbol:   class ServiceException
  location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[19,38] cannot find symbol
  symbol:   method findAll()
  location: variable userRepository of type br.com.example.repository.UserRepository
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[23,38] cannot find symbol
  symbol:   method findOne(java.lang.Integer)
  location: variable userRepository of type br.com.example.repository.UserRepository
[INFO] 55 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] spring-boot-generate ............................... FAILURE [  2.484 s]
[INFO] spring-scaffold-cli ................................ SKIPPED
[INFO] Spring generate api scaffold kotlin ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.024 s
[INFO] Finished at: 2017-06-16T00:21:21+08:00
[INFO] Final Memory: 24M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project spring-boot-generate: Compilation failure: Compilation failure:
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/repository/UserRepository.java:[3,47] package org.springframework.data.jpa.repository does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[5,24] package javax.validation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[7,33] package org.hibernate.service.spi does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[12,47] package org.springframework.web.bind.annotation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[13,47] package org.springframework.web.bind.annotation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[14,47] package org.springframework.web.bind.annotation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[15,47] package org.springframework.web.bind.annotation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[16,47] package org.springframework.web.bind.annotation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[17,47] package org.springframework.web.bind.annotation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[18,47] package org.springframework.web.bind.annotation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[19,51] package org.springframework.web.servlet.mvc.support does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[20,28] package br.com.example.model does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[24,2] cannot find symbol
[ERROR] symbol: class RequestMapping
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[4,47] package org.springframework.data.jpa.repository does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[6,28] package br.com.example.model does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[8,50] package org.springframework.transaction.annotation does not exist
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[12,2] cannot find symbol
[ERROR] symbol: class Transactional
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[52,59] cannot find symbol
[ERROR] symbol:   class User
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[58,53] cannot find symbol
[ERROR] symbol:   class User
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[58,88] cannot find symbol
[ERROR] symbol:   class RedirectAttributes
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[84,53] cannot find symbol
[ERROR] symbol:   class User
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[84,88] cannot find symbol
[ERROR] symbol:   class RedirectAttributes
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[97,62] cannot find symbol
[ERROR] symbol:   class RedirectAttributes
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[18,21] cannot find symbol
[ERROR] symbol:   class User
[ERROR] location: class br.com.example.service.UserService
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[22,16] cannot find symbol
[ERROR] symbol:   class User
[ERROR] location: class br.com.example.service.UserService
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[27,26] cannot find symbol
[ERROR] symbol:   class User
[ERROR] location: class br.com.example.service.UserService
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[27,16] cannot find symbol
[ERROR] symbol:   class User
[ERROR] location: class br.com.example.service.UserService
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[32,28] cannot find symbol
[ERROR] symbol:   class User
[ERROR] location: class br.com.example.service.UserService
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[35,10] cannot find symbol
[ERROR] symbol:   class GetMapping
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[43,42] cannot find symbol
[ERROR] symbol:   class PathVariable
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[42,10] cannot find symbol
[ERROR] symbol:   class GetMapping
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[52,44] cannot find symbol
[ERROR] symbol:   class ModelAttribute
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[51,10] cannot find symbol
[ERROR] symbol:   class GetMapping
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[58,31] cannot find symbol
[ERROR] symbol:   class Valid
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[58,38] cannot find symbol
[ERROR] symbol:   class ModelAttribute
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[57,10] cannot find symbol
[ERROR] symbol:   class PostMapping
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[71,44] cannot find symbol
[ERROR] symbol:   class PathVariable
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[70,10] cannot find symbol
[ERROR] symbol:   class GetMapping
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[84,31] cannot find symbol
[ERROR] symbol:   class Valid
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[84,38] cannot find symbol
[ERROR] symbol:   class ModelAttribute
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[83,10] cannot find symbol
[ERROR] symbol:   class PutMapping
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[97,31] cannot find symbol
[ERROR] symbol:   class PathVariable
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[96,10] cannot find symbol
[ERROR] symbol:   class DeleteMapping
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[26,10] cannot find symbol
[ERROR] symbol:   class Transactional
[ERROR] location: class br.com.example.service.UserService
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[31,10] cannot find symbol
[ERROR] symbol:   class Transactional
[ERROR] location: class br.com.example.service.UserService
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[37,22] cannot find symbol
[ERROR] symbol:   class User
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[45,25] cannot find symbol
[ERROR] symbol:   class User
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[59,17] cannot find symbol
[ERROR] symbol:   class User
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[74,33] cannot find symbol
[ERROR] symbol:   class User
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[78,35] cannot find symbol
[ERROR] symbol:   class ServiceException
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[85,17] cannot find symbol
[ERROR] symbol:   class User
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[100,33] cannot find symbol
[ERROR] symbol:   class User
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[106,35] cannot find symbol
[ERROR] symbol:   class ServiceException
[ERROR] location: class br.com.example.controller.UserController
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[19,38] cannot find symbol
[ERROR] symbol:   method findAll()
[ERROR] location: variable userRepository of type br.com.example.repository.UserRepository
[ERROR] /C:/projects/cli-spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[23,38] cannot find symbol
[ERROR] symbol:   method findOne(java.lang.Integer)
[ERROR] location: variable userRepository of type br.com.example.repository.UserRepository
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by NetoDevel** [comment]
Some teste is failing, try using `mvn install -Dmaven.test.skip=true`, while i'm working to fix this.

**Comment by NetoDevel** [comment]
@borgymanotoy fixed.

**Comment by shingokuniyoshi** [comment]
Still showing above errors in my situation(windows 10)
So I did `mvn install -Dmaven.test.skip=true`

**Comment by NetoDevel** [comment]
@shingokuniyoshi Okay, I'll take a look.
please if you intend to contribute, look at this repository:
https://github.com/NetoDevel/generate-core
