### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by 8904591612** [NetoDevel/cli-spring-boot-scaffold#31]
Thanks a lot for the scaffolding .I followed all the instructions , but it says "Whitelabel Error Page" when I navigate to localhost:8080/users. .I have followed all the steps given in the tutorial.What may be the issue I am unable to make out please help

**Comment by NetoDevel** [comment]
Is it probably a thymeleaf error, send me the source of the index.html file?

**Comment by 8904591612** [comment]
my-project/src/main/resources/templates/data/index.html.This is the source  of the index.html file

I have already created my database and tables ,  the  name of table is "datas".  It is already filled with data. I  navigated to  localhost:8080/datas . It is throwing the  same error. The error is " Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback."

But when I create the user table   using the scaffold command it is working.
Is it that I can use it for  already existing tables?

**Comment by NetoDevel** [comment]
Could you upload your project to git? I need to look at the code.

**Comment by 8904591612** [comment]
https://github.com/8904591612/Spring-Scaffold. 

This is the link to my git repository

**Comment by NetoDevel** [comment]
thank`s, i will clone your repository

**Comment by NetoDevel** [comment]
@8904591612 hey i found of the error, your **DemoApplication.class** it is inside of package `mynewproject`, please put your **DemoApplication.class** inside `com.example` to find other routes.
