### ISSUE TITLE
how create mongodb dependencies

### ISSUE THREAD

**Issue by publicocean0** [NetoDevel/cli-spring-boot-scaffold#36]

**Comment by NetoDevel** [comment]
for create the project with depedency of mongodb just run the command:
`spring init --dependencies=web,data-jpa,thymeleaf,mongodb my-project`
but the scaffold not support mongo db, you should adapt.

**Comment by publicocean0** [comment]
20:44:04.000 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Encoding: gzip
20:44:04.000 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Vary: Accept-Encoding
20:44:04.000 [main] DEBUG org.apache.http.headers - http-outgoing-0 << X-Application-Context: start-blue:cloud:1
20:44:04.000 [main] DEBUG org.apache.http.headers - http-outgoing-0 << X-Vcap-Request-Id: 4fb8d9c4-1431-49f5-5d61-b94c54eca26a
20:44:04.000 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Server: cloudflare-nginx
20:44:04.000 [main] DEBUG org.apache.http.headers - http-outgoing-0 << CF-RAY: 39596b71da244346-MXP
20:44:04.001 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
20:44:04.043 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection [id: 0][route: {s}->https://start.spring.io:443] can be kept alive indefinitely
20:44:04.043 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://start.spring.io:443][total kept alive: 1; route allocated: 1 of 5; total allocated: 1 of 10]
Initializr service call failed using 'https://start.spring.io' - service returned Bad Request: 'Unknown dependency 'mongodb' check project metadata'

**Comment by publicocean0** [comment]
thanks it will be very usefull a template for mongodb

**Comment by NetoDevel** [comment]
@publicocean0 could you show me a simple crud spring boot with mongodb?
