### ISSUE TITLE
redundant templates found

### ISSUE THREAD

**Issue by dominik42** [NetoDevel/cli-spring-boot-scaffold#40]
Hi,
after a 3 day deep dive into angular/typescript I was very impressed by the angular cli for generating all kinds of artifacts needed by angular apps. Mainly, I'm a Spring Boot backend developer so I was looking around for a similar solution for Spring Boot and found your project. Nice work until now, thank you !!! I've just cloned the repo and start playing around. My first question: why the Thymeleaf templates are exists in booth projects, spring-boot-generate AND spring-scaffold-cli ? As I assume, spring-scaffold-cli is the integration into the Spring Boot CLI and the real work is done by spring-boot-generate, right ? So should the templates better resists in spring-boot-generate only ?

Greetings from Germany
Dominik

**Comment by NetoDevel** [comment]
Hi, Thanks
yes the real work is spring-boot-generate, and right now I'm working a new core extensible and easy-maintenance .
so that the community can contribute with some templates to the generate...
Please access this link to see how the new core of the project
https://github.com/NetoDevel/generate-core

**Comment by dominik42** [comment]
… sounds good. Can I use it already from the command line ? With or without spring-boot-cli ?
Or should I continue using the existing one ?

BTW, why there are GeneratorXYZ.java and GeneratorCleanXYZ.java ? Whats the reason behind that difference ?

kind regards
Dominik

**Comment by NetoDevel** [comment]
@dominik42 
Generates Clean are simple classes instead of being a full CRUD.
Just see the difference in the templates.
https://github.com/NetoDevel/generate-core/tree/master/src/main/resources/templates/java/controller

**Comment by dominik42** [comment]
… ah … got it 

kind regards
Dominik

**Comment by NetoDevel** [comment]
@dominik42, enter the gitter, there we can talk more about.
`In the project readme has the link to the gitter.`
