### ISSUE TITLE
Generated scaffolding doesn't work

### ISSUE THREAD

**Issue by artgo** [NetoDevel/cli-spring-boot-scaffold#41]
1. Generate a new spring boot project;
2. spring setup:scaffold
3. spring scaffold -n "User" -p "name:String email:String"
4. spring db:create -p "mysql"
5. mvn spring-boot:run

The generated controller returns 404 on http://localhost:8080/users

**Comment by artgo** [comment]
Figured it out. Needed to add Themeleaf to the project. This needs to be explicitly stated in the documentation.

**Comment by NetoDevel** [comment]
@artgo, Did you start the project with a cli too?

`$ spring init --dependencies = web, data-jpa, thymeleaf, mysql - package-name = com.example my-project
`

At that point it already adds to dependency on thymelaf.

**Comment by NetoDevel** [comment]
closed by inactivity of the owner of the issue.
