### ISSUE TITLE
Is it a good idea to implement the application tests to crud?

### ISSUE THREAD

**Issue by thiagogomesverissimo** [NetoDevel/cli-spring-boot-scaffold#47]

**Comment by NetoDevel** [comment]
@thiagogomesverissimo, 
Yes, that's a good idea.

**Comment by NetoDevel** [comment]
@thiagogomesverissimo, i think it's a good idea to generate integration and contract tests.

**Comment by NetoDevel** [comment]
closed by inactivity.
