### ISSUE TITLE
mvn install ERROR ERROR ERROR!

### ISSUE THREAD

**Issue by danilomeneghel** [NetoDevel/cli-spring-boot-scaffold#54]
[INFO] 18 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] spring-boot-generate 0.0.1-SNAPSHOT ................ FAILURE [ 42.815 s]
[INFO] spring-scaffold-cli 0.0.1-SNAPSHOT ................. SKIPPED
[INFO] Spring generate api scaffold kotlin 0.0.1.BUILD-SNAPSHOT SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.144 s
[INFO] Finished at: 2018-10-24T19:01:11-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5:compile (default-compile) on project spring-boot-generate: Compilation failure: Compilation failure:
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[6,28] package br.com.example.model does not exist
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[18,21] cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class br.com.example.service.UserService
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[22,16] cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class br.com.example.service.UserService
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[27,26] cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class br.com.example.service.UserService
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[27,16] cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class br.com.example.service.UserService
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[32,28] cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class br.com.example.service.UserService
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[20,28] package br.com.example.model does not exist
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[52,59] cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class br.com.example.controller.UserController
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[58,53] cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class br.com.example.controller.UserController
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[84,53] cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class br.com.example.controller.UserController
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[19,38] cannot find symbol
[ERROR]   symbol:   method findAll()
[ERROR]   location: variable userRepository of type br.com.example.repository.UserRepository
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/service/UserService.java:[23,38] cannot find symbol
[ERROR]   symbol:   method findOne(java.lang.Integer)
[ERROR]   location: variable userRepository of type br.com.example.repository.UserRepository
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[37,22] cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class br.com.example.controller.UserController
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[45,25] cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class br.com.example.controller.UserController
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[59,17] cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class br.com.example.controller.UserController
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[74,33] cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class br.com.example.controller.UserController
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[85,17] cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class br.com.example.controller.UserController
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot-scaffold/spring-boot-generate/src/main/java/br/com/example/controller/UserController.java:[100,33] cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class br.com.example.controller.UserController
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by NetoDevel** [comment]
Track a issue #53

**Comment by danilomeneghel** [comment]
ok, and...

'setup:scaffold' is not a valid command. See 'help'.

**Comment by danilomeneghel** [comment]
Create tables in db, manual, but...

1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.104 s
[INFO] Finished at: 2018-10-24T20:51:08-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project my-project: Compilation failure
[ERROR] /C:/Users/danil/Documents/NetBeansProjects/spring-boot/my-project/src/main/java/com/example/service/UserService.java:[23,38] method findOne in interface org.springframework.data.repository.query.QueryByExampleExecutor<T> cannot be applied to given types;
[ERROR]   required: org.springframework.data.domain.Example<S>
[ERROR]   found: java.lang.Integer
[ERROR]   reason: cannot infer type-variable(s) S
[ERROR]     (argument mismatch; java.lang.Integer cannot be converted to org.springframework.data.domain.Example<S>)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

mvn spring-boot:run

**Comment by danilomeneghel** [comment]
Can you help me because the project does not work?

**Comment by NetoDevel** [comment]
@danilomeneghel, Fix the problem when running mvn install, on your other error above is due to new interface from `spring-data-jpa` to version 2.x.x of spring boot.

Replace in your code the `findOne `method for `findById`
